[package]
name = "keyring"
description = "Personal key management server"
version = "0.1.0"
license = "AGPL"
authors = ["Dr. Maxim Orlovsky <orlovsky@pandoracore.com>"]
keywords = ["bitcoin", "secp256k1", "ecdsa", "schnorr"]
edition = "2018"
readme = "README.md"

[[bin]]
name = "keyringd"
required-features = ["server"]

[[bin]]
name = "keyring-cli"
required-features = ["integration", "cli"]

[dependencies]
amplify = "=1.0.0-beta.1"
amplify_derive = "=1.0.0-beta.1"
dotenv = { version = "~0.15.0", optional = true }
clap = { version = "=3.0.0-beta.2", optional = true }
serde = { version = "~1.0.111", features = ["derive"] }
serde_with = "~1.4.0"
serde_json = { version = "~1.0.55", optional = true }
serde_yaml = { version = "~0.8.13", optional = true }
toml = { version = "~0.5.6", optional = true }
settings = { version = "~0.10.1", package = "config", optional = true }
bech32 = { version = "~0.7.2", optional = true }
base64 = { version = "~0.12.1", optional = true }
log = { version = "~0.4.8", features = ["max_level_trace", "release_max_level_debug"], optional = true }
env_logger = { version = "~0.7.1", optional = true }
async-trait = "~0.1.35"
regex = { version = "~1.3.9", optional = true }
num-traits = "~0.2.11"
num-derive = "~0.3.0"
tokio = { version = "~0.2.21", features = ["full"] }
futures = "~0.3.5"
zmq = "~0.9.2"
tiny_http = { version = "~0.7.0", optional = true }
prometheus = { version = "~0.9.0", optional = true }
lazy_static = "~1.4.0"

[dependencies.lnpbp]
git = "https://github.com/LNP-BP/rust-lnpbp"
branch = "master"
features = ["tor", "lnp", "tokio", "url", "daemons", "serde", "keygen", "websockets"]

[dependencies.lnpbp_derive]
git = "https://github.com/lnp-bp/rust-lnpbp"
branch = "master"

[features]
default = []
all = ["server", "monitoring", "integration"]
integration = []
server = ["daemon", "cli", "lnpbp/log", "lnpbp/parse_arg"]
cli = ["shell", "base64"]
daemon = ["shell", "settings"]
shell = ["dotenv", "clap", "serde_json", "serde_yaml", "toml", "bech32", "log", "regex", "env_logger"]
monitoring = ["prometheus", "tiny_http"]
