# Default keyring daemon configuration file
[generic]
data_dir = "./data"
log = "verbose"

[vault]
driver = "file"

[vault.file]
location = "{data_dir}/vault.dat"

[client.cli]
connect = "ipc"
allow = [ "all" ]
second_auth_seed = ""

[client.user1]
connect = "all"
keys = [ "" ]
nodes = [ ]
allow = [ "seed", "read", "derive", "sign" ]
second_auth_seed = ""
