# Default keyring daemon configuration file

node_key = "87c00b999b6439e56f893856133fd23d9d78851070051cd2136fa4a555658ae0"
data_dir = "./data"
log_level = "Trace"
zmq_endpoint = "ipc:./data/zmq.rpc"
tcp_endpoint = "0.0.0.0:20202"

[vault]
driver = "File"
location = "vault.yaml"
format = "Yaml"

[client.cli]
connect = "ipc"
allow = [ "all" ]
second_auth_seed = ""

[client.user1]
connect = "all"
keys = [ "" ]
semilock = ""
halfunlock = ""
nodes = [ ]
allow = [ "seed", "read", "derive", "sign" ]
second_auth_seed = ""
